spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: GCjygdSyI3=o
    url: jdbc:mysql://127.0.0.1:3306/springCloud_Sell?characterEnconding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url: http://localhost:8761/eureka/
